from typing import Any

BUILTIN_MANIFESTS: list[dict[str, Any]] = [
    {
        "plugin_id": "aiops-x.network-rest",
        "name": "Network Operations REST Adapter",
        "version": "1.0.0",
        "vendor": "AIOps-X",
        "description": "网络发现、端口状态、路径与配置备份系统的受控 REST 适配器。",
        "capabilities": ["discovery", "collector", "health_check", "query"],
        "supported_asset_types": ["network_device", "firewall", "load_balancer"],
        "configuration_schema": {"type": "object", "required": ["operations"]},
        "credential_types": ["bearer_token", "basic_auth"],
        "required_permissions": ["plugin:invoke", "network:read"],
        "risk_level": "R0",
        "timeout": 30,
        "retry_policy": {"max_attempts": 3, "backoff_seconds": 2},
        "idempotent": True,
        "health_check": {"method": "GET", "path": "/health"},
        "entrypoint": "aiops_x.plugins.http_json_v1",
    },
    {
        "plugin_id": "aiops-x.windows-rest",
        "name": "Windows Operations Gateway Adapter",
        "version": "1.0.0",
        "vendor": "AIOps-X",
        "description": "通过隔离的 WinRM/WMI Gateway 查询服务、事件、补丁、磁盘与进程。",
        "capabilities": ["collector", "health_check", "query"],
        "supported_asset_types": ["windows"],
        "configuration_schema": {"type": "object", "required": ["operations"]},
        "credential_types": ["bearer_token"],
        "required_permissions": ["plugin:invoke", "windows:read"],
        "risk_level": "R0",
        "timeout": 45,
        "retry_policy": {"max_attempts": 2, "backoff_seconds": 3},
        "idempotent": True,
        "health_check": {"method": "GET", "path": "/health"},
        "entrypoint": "aiops_x.plugins.http_json_v1",
    },
    {
        "plugin_id": "aiops-x.docker-api",
        "name": "Docker Engine Gateway Adapter",
        "version": "1.0.0",
        "vendor": "AIOps-X",
        "description": (
            "通过受 TLS 保护的 Docker Gateway 查询容器、镜像、网络、卷、日志与健康状态。"
        ),
        "capabilities": ["discovery", "collector", "health_check", "query"],
        "supported_asset_types": ["docker"],
        "configuration_schema": {"type": "object", "required": ["operations"]},
        "credential_types": ["mtls", "bearer_token"],
        "required_permissions": ["plugin:invoke", "docker:read"],
        "risk_level": "R0",
        "timeout": 30,
        "retry_policy": {"max_attempts": 2, "backoff_seconds": 2},
        "idempotent": True,
        "health_check": {"method": "GET", "path": "/health"},
        "entrypoint": "aiops_x.plugins.http_json_v1",
    },
    {
        "plugin_id": "aiops-x.kubernetes-api",
        "name": "Kubernetes Read-only Gateway Adapter",
        "version": "1.0.0",
        "vendor": "AIOps-X",
        "description": (
            "限定集群和 Namespace 的 Kubernetes 只读发现、事件、日志与资源利用率适配器。"
        ),
        "capabilities": ["discovery", "collector", "health_check", "query"],
        "supported_asset_types": ["kubernetes_cluster", "pod"],
        "configuration_schema": {"type": "object", "required": ["operations", "namespace_scope"]},
        "credential_types": ["service_account_token", "mtls"],
        "required_permissions": ["plugin:invoke", "kubernetes:read"],
        "risk_level": "R0",
        "timeout": 30,
        "retry_policy": {"max_attempts": 2, "backoff_seconds": 2},
        "idempotent": True,
        "health_check": {"method": "GET", "path": "/healthz"},
        "entrypoint": "aiops_x.plugins.http_json_v1",
    },
    {
        "plugin_id": "aiops-x.database-readonly",
        "name": "Database Read-only Gateway Adapter",
        "version": "1.0.0",
        "vendor": "AIOps-X",
        "description": (
            "PostgreSQL、MySQL、Oracle、SQL Server、Redis 与 MongoDB 的只读状态查询适配器。"
        ),
        "capabilities": ["collector", "health_check", "query"],
        "supported_asset_types": ["database"],
        "configuration_schema": {"type": "object", "required": ["operations", "read_only"]},
        "credential_types": ["database_readonly"],
        "required_permissions": ["plugin:invoke", "database:read"],
        "risk_level": "R0",
        "timeout": 30,
        "retry_policy": {"max_attempts": 2, "backoff_seconds": 2},
        "idempotent": True,
        "health_check": {"method": "GET", "path": "/health"},
        "entrypoint": "aiops_x.plugins.http_json_v1",
    },
    {
        "plugin_id": "aiops-x.security-findings",
        "name": "Security Findings Adapter",
        "version": "1.0.0",
        "vendor": "AIOps-X",
        "description": "Wazuh、Greenbone、Nuclei、ZAP、Trivy 与 DefectDojo 发现项标准化适配器。",
        "capabilities": ["collector", "health_check", "query"],
        "supported_asset_types": ["security_device", "application", "custom"],
        "configuration_schema": {"type": "object", "required": ["operations"]},
        "credential_types": ["api_token"],
        "required_permissions": ["plugin:invoke", "security:read"],
        "risk_level": "R0",
        "timeout": 60,
        "retry_policy": {"max_attempts": 3, "backoff_seconds": 5},
        "idempotent": True,
        "health_check": {"method": "GET", "path": "/health"},
        "entrypoint": "aiops_x.plugins.http_json_v1",
    },
    {
        "plugin_id": "aiops-x.notification-rest",
        "name": "Notification REST Adapter",
        "version": "1.0.0",
        "vendor": "AIOps-X",
        "description": "通过受控 REST 网关发送邮件、短信、即时通信或工单通知并保留回执证据。",
        "capabilities": ["health_check", "notification"],
        "supported_asset_types": [],
        "configuration_schema": {"type": "object", "required": ["operations"]},
        "credential_types": ["api_token", "bearer_token"],
        "required_permissions": ["plugin:invoke", "notification:send"],
        "risk_level": "R1",
        "timeout": 30,
        "retry_policy": {"max_attempts": 3, "backoff_seconds": 3},
        "idempotent": True,
        "health_check": {"method": "GET", "path": "/health"},
        "entrypoint": "aiops_x.plugins.http_json_v1",
    },
]
