{{- if .Values.externalSecrets.enabled }}
{{- range $name, $remoteKey := .Values.externalSecrets.remoteKeys }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "aiops-x.fullname" $ }}-{{ $name | kebabcase }}
  labels: {{- include "aiops-x.labels" $ | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $.Values.externalSecrets.secretStoreRef }}
    kind: ClusterSecretStore
  target:
    name: {{ index $.Values.existingSecrets $name }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ $remoteKey }}
---
{{- end }}
{{- end }}
