apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aiops-x.fullname" . }}-api
  labels: {{- include "aiops-x.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aiops-x.fullname" . }}-worker
  labels: {{- include "aiops-x.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aiops-x.fullname" . }}-ai-engine
  labels: {{- include "aiops-x.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aiops-x.fullname" . }}-web
  labels: {{- include "aiops-x.labels" . | nindent 4 }}
automountServiceAccountToken: false
